SELECT date_format(sales_date, '%Y-%m-%d') as sales_date, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

UNION ALL

SELECT date_format(sales_date, '%Y-%m-%d') as sales_dateE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID