-- 코드를 입력하세요
SELECT T.BOOK_ID, S.AUTHOR_NAME, DATE_FORMAT(T.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
    FROM BOOK T
    JOIN AUTHOR S
    ON T.AUTHOR_ID = S.AUTHOR_ID
    WHERE T.CATEGORY = '경제'
    ORDER BY T.PUBLISHED_DATE